#!/usr/bin/env python3
"""Extract the verbatim lookup tables (finesine/finetangent/tantoangle) from
reference/linuxdoom-1.10/tables.c into src/tables.js.

These 1995 literals are NOT reproducible from JS math: Math.sin rounds at
different places than the original (33 finesine entries off by 1), and the
tantoangle approximation is off by >=1 BAM on 1880/2049 entries — enough to
rotate monster faces and deflect missiles relative to a vanilla recording.
Embed them instead.

usage: python3 tools/extract_tables.py [out]
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'reference', 'linuxdoom-1.10', 'tables.c')
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'src', 'tables.js')

src = open(SRC).read()


def grab(sym):
    m = re.search(r'(?:unsigned short|int|angle_t|fixed_t)\s+' + sym +
                  r'\s*\[[^\]]*\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not m:
        sys.exit('tables.c: array %s not found' % sym)
    vals = [int(v, 16) if v.lower().startswith('0x') else int(v)
            for v in re.findall(r'0[xX][0-9a-fA-F]+|-?\d+', m.group(1))]
    return vals


fs = grab('finesine')
ft = grab('finetangent')
ta = grab('tantoangle')
assert len(fs) == 10240, len(fs)
assert len(ft) == 4096, len(ft)
assert len(ta) == 2049, len(ta)


def emit(name, vals, width=20):
    lines = ['  %s: [' % name]
    for i in range(0, len(vals), width):
        lines.append('    ' + ','.join(str(v) for v in vals[i:i + width]) + ',')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('  ],')
    return lines


out = []
out.append('// GENERATED by tools/extract_tables.py — do not edit.')
out.append('// Verbatim tables.c literals (finesine[10240], finetangent[4096],')
out.append('// tantoangle[2049]). Vanilla movement/aim reads these exact values;')
out.append('// JS-computed trig drifts up to 1 BAM and shifts routes/aim.')
out.append('var VANILLA_TABLES = {')
out += emit('finesine', fs)
out += emit('finetangent', ft)
out += emit('tantoangle', ta)
out.append('};')
out.append('if (typeof globalThis !== "undefined") globalThis.VANILLA_TABLES = VANILLA_TABLES;')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w').write('\n'.join(out) + '\n')
print('wrote %s (%d/%d/%d entries)' % (OUT, len(fs), len(ft), len(ta)))
