#!/usr/bin/env python3
"""Extract the title/menu/demo lumps (m_menu.c patches + d_main.c DEMOn
lumps) from a DOOM WAD into assets/title.js. Same conventions as
extract_intermission.py (PLAYPAL-indexed bytes, 255=transparent).

usage: python3 tools/extract_title.py [wad] [out]
"""
import base64
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wad_assets

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# every patch m_menu.c caches (skull cursor, thermo, save/load border, all
# menu item names, help screens) + d_main.c pages (TITLEPIC; HELP1 is the
# shareware ReadThis page). CREDIT + STCFN glyphs already live in
# assets/intermission.js (INTERLUDE) — menu.js reads them from there.
MENU_LUMPS = [
    'TITLEPIC', 'HELP1', 'HELP2',
    'M_DOOM', 'M_NGAME', 'M_OPTION', 'M_LOADG', 'M_SAVEG', 'M_RDTHIS',
    'M_QUITG', 'M_EPISOD', 'M_EPI1', 'M_EPI2', 'M_EPI3', 'M_EPI4',
    'M_NEWG', 'M_SKILL', 'M_JKILL', 'M_ROUGH', 'M_HURT', 'M_ULTRA',
    'M_NMARE', 'M_ENDGAM', 'M_MESSG', 'M_DETAIL', 'M_SCRNSZ', 'M_MSENS',
    'M_SVOL', 'M_SFXVOL', 'M_MUSVOL', 'M_GDHIGH', 'M_GDLOW', 'M_MSGOFF',
    'M_MSGON', 'M_OPTTTL', 'M_SKULL1', 'M_SKULL2', 'M_PAUSE',
    'M_THERML', 'M_THERMM', 'M_THERMR', 'M_THERMO',
    'M_LSLEFT', 'M_LSCNTR', 'M_LSRGHT', 'M_LOAD', 'M_SAVE',
]
DEMOS = ['DEMO1', 'DEMO2', 'DEMO3']


def main():
    wadpath = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'wads/doom1.wad')
    outpath = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'assets/title.js')
    wad = wad_assets.Wad(wadpath)
    patches = {}
    missing = []
    for name in MENU_LUMPS:
        raw, _ = wad.get(name)
        if raw is None:
            missing.append(name)
            continue
        d = wad_assets.decode_patch(raw)
        if d is None:
            missing.append(name + ' (undecodable)')
            continue
        w, h, px, left, top = d
        patches[name] = (w, h, bytes(px), left, top)
    demos = {}
    for name in DEMOS:
        raw, _ = wad.get(name)
        if raw is None:
            missing.append(name)
            continue
        demos[name] = bytes(raw)
    # M_EPI4 is absent from the shareware WAD (vanilla M_Init trims the 4th
    # episode); M_LOAD/M_SAVE icons aren't drawn by this port's HUD.
    soft_missing = [m for m in missing if m in ('M_LOAD', 'M_SAVE', 'M_EPI4')]
    missing = [m for m in missing if m not in soft_missing]
    if missing:
        print('MISSING:', missing)
        sys.exit(1)

    buf = []
    buf.append('// AUTO-GENERATED by tools/extract_title.py — verbatim WAD menu/title\n')
    buf.append('// patches and DEMO1-3 lumps from %s.\n' % os.path.basename(wadpath))
    buf.append('const TITLE = {\n  patches: {\n')
    for name in sorted(patches):
        w, h, px, left, top = patches[name]
        buf.append('    "%s": [%d,%d,"%s",%d,%d],\n'
                   % (name, w, h, base64.b64encode(px).decode(), left, top))
    buf.append('  },\n  demos: {\n')
    for name in sorted(demos):
        buf.append('    "%s": "%s",\n' % (name, base64.b64encode(demos[name]).decode()))
    buf.append('  }\n};\n')
    buf.append('globalThis.TITLE = TITLE;   // expose const for vm/CDP\n')
    open(outpath, 'w').write(''.join(buf))
    print('title.js written: %d patches + %d demos, %d bytes%s'
          % (len(patches), len(demos), os.path.getsize(outpath),
             (' (soft-missing %s)' % soft_missing) if soft_missing else ''))


if __name__ == '__main__':
    main()
