#!/usr/bin/env python3
"""Extract the intermission/finale patch lumps (wi_stuff.c WI_loadData +
f_finale.c font/CREDIT) straight from a DOOM WAD into assets/intermission.js.
Same conventions as extract_statusbar.py: PLAYPAL-indexed bytes, 255=transparent.

usage: python3 tools/extract_intermission.py [wad] [out]
"""
import base64
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wad_assets

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def intermission_lump_names():
    need = ['WIMAP0']                                    # epsd-1 world map bg
    need += ['WILV0%d' % i for i in range(9)]            # "E1Mn" title patches
    for j in range(10):                                  # epsd0 anims (10x3)
        for i in range(3):
            need.append('WIA0%02d%02d' % (j, i))  # sprintf("WIA%d%.2d%.2d", 0, j, i)
    need += ['WIURH0', 'WIURH1', 'WISPLAT']
    need += ['WINUM%d' % i for i in range(10)]
    need += ['WIPCNT', 'WICOLON', 'WISUCKS', 'WIMINUS']
    need += ['WIF', 'WIENTER', 'WIOSTK', 'WIOSTI', 'WIOSTS', 'WISCRT2']
    need += ['WITIME', 'WIPAR']
    # hu_font (hu_stuff.c:394): STCFN%.3d for '!' (33) .. '_' (95)
    need += ['STCFN%.3d' % c for c in range(33, 96)]
    need += ['CREDIT']                                   # E1 finale stage 1
    return need


def main():
    wadpath = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'wads/doom1.wad')
    outpath = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'assets/intermission.js')
    wad = wad_assets.Wad(wadpath)
    out = {'patches': {}}
    missing = []
    for name in intermission_lump_names():
        raw, _ = wad.get(name)
        if raw is None:
            missing.append(name)
            continue
        d = wad_assets.decode_patch(raw)
        if d is None:
            missing.append(name + ' (undecodable)')
            continue
        w, h, px, left, top = d
        out['patches'][name] = (w, h, bytes(px), left, top)
    # finale background flat (f_finale.c F_StartFinale: finaleflat "FLOOR4_8")
    flat_raw, _ = wad.get('FLOOR4_8')
    flat = bytes(flat_raw) if flat_raw is not None else None
    if flat is None or len(flat) != 64 * 64:
        missing.append('FLOOR4_8')
    if missing:
        print('MISSING:', missing)
        sys.exit(1)

    buf = []
    buf.append('// AUTO-GENERATED by tools/extract_intermission.py — verbatim WAD\n')
    buf.append('// intermission/finale patches from %s (PLAYPAL-indexed bytes; 255=transparent).\n'
               % os.path.basename(wadpath))
    buf.append('const INTERLUDE = {\n  patches: {\n')
    for name in sorted(out['patches']):
        w, h, px, left, top = out['patches'][name]
        b64 = base64.b64encode(px).decode()
        buf.append('    "%s": [%d,%d,"%s",%d,%d],\n' % (name, w, h, b64, left, top))
    buf.append('  },\n  flat: "%s"\n};\n' % base64.b64encode(flat).decode())
    buf.append('globalThis.INTERLUDE = INTERLUDE;   // expose const for vm/CDP\n')
    open(outpath, 'w').write(''.join(buf))
    print('intermission.js written: %d patches + flat, %d bytes'
          % (len(out['patches']), os.path.realpath(outpath) and os.path.getsize(outpath)))


if __name__ == '__main__':
    main()
