#!/usr/bin/env python3
"""Extract the status-bar patch lumps (st_stuff.c ST_initData list) straight
from a DOOM WAD into assets/statusbar.js — no procedural re-generation.
Pixel bytes are vanilla PLAYPAL indices; 255 = transparent (post gaps).

usage: python3 tools/extract_statusbar.py [wad] [out]
"""
import base64
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import wad_assets

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def statusbar_lump_names():
    need = ['STBAR', 'STFB0', 'STTPRCNT', 'STTMINUS', 'STARMS']
    need += ['AMMNUM%d' % i for i in range(10)]    # am_map.c AM_loadPics
    need += ['STTNUM%d' % i for i in range(10)]
    need += ['STYSNUM%d' % i for i in range(10)]
    need += ['STKEYS%d' % i for i in range(6)]
    need += ['STGNUM%d' % i for i in range(2, 8)]
    need += ['STFGOD0', 'STFDEAD0']
    # r_draw.c R_FillBackScreen bevel patches (view border, screenblocks < 11)
    need += ['BRDR_T', 'BRDR_B', 'BRDR_L', 'BRDR_R',
             'BRDR_TL', 'BRDR_TR', 'BRDR_BL', 'BRDR_BR']
    for i in range(5):                       # ST_NUMPAINFACES
        for j in range(3):                   # ST_NUMSTRAIGHTFACES
            need.append('STFST%d%d' % (i, j))
        need += ['STFTR%d0' % i, 'STFTL%d0' % i, 'STFOUCH%d' % i,
                 'STFEVL%d' % i, 'STFKILL%d' % i]
    return need


def main():
    wadpath = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'wads/Doom1.wad')
    outpath = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'assets/statusbar.js')
    wad = wad_assets.Wad(wadpath)
    out = {'patches': {}}
    missing = []
    for name in statusbar_lump_names():
        raw, _ = wad.get(name)
        if raw is None:
            missing.append(name)
            continue
        d = wad_assets.decode_patch(raw)
        if d is None:
            missing.append(name + ' (undecodable)')
            continue
        w, h, px, left, top = d
        out['patches'][name] = (w, h, bytes(px), left, top)
    if missing:
        print('MISSING:', missing)
        sys.exit(1)

    buf = []
    buf.append('// AUTO-GENERATED by tools/extract_statusbar.py — verbatim WAD\n')
    buf.append('// status-bar patches from %s (PLAYPAL-indexed bytes; 255=transparent).\n'
               % os.path.basename(wadpath))
    buf.append('const STATUSBAR = {\n  patches: {\n')
    for name in sorted(out['patches']):
        w, h, px, left, top = out['patches'][name]
        b64 = base64.b64encode(px).decode()
        buf.append('    "%s": [%d,%d,"%s",%d,%d],\n' % (name, w, h, b64, left, top))
    buf.append('  }\n};\n')
    open(outpath, 'w').write(''.join(buf))
    print('statusbar.js written: %d patches, %d bytes'
          % (len(out['patches']), os.path.getsize(outpath)))


if __name__ == '__main__':
    main()
