#!/usr/bin/env python3
"""Extract audio from the IWAD into assets/audio.js.

Contents (all base64 of raw lump bytes — decoders live in audio.js):
  ASSETS.sounds  { PISTOL: "...", ... }   DS* lumps (DMX header kept intact)
  ASSETS.genmidi "..."                     GENMIDI lump (OPL2 instrument bank)
  ASSETS.music   { E1M1: "...", ... }      D_* MUS lumps
Vanilla names sfx lumps as "ds"+name (sounds.c/i_sound.c:201) and music as
"d_"+name (s_sound.c:674), so we store the suffix only.
"""
import base64
import struct
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wad_assets import Wad


def main():
    wad = Wad(os.path.join(os.path.dirname(__file__), "..", "wads", "doom1.wad"))

    def lumps_with(prefix):
        for name, off, size in wad.lumps:
            if name.startswith(prefix) and size:
                yield name, wad.data[off:off + size]

    out = []
    out.append("// assets/audio.js — generated by tools/gen_audio.py from wads/doom1.wad.\n")
    out.append("// Raw lump bytes, base64. Decoders (DMX8, MUS, GENMIDI, dbopl) live in audio.js.\n")
    out.append("ASSETS.sounds = {\n")
    n = 0
    for name, data in lumps_with("DS"):
        out.append('  %s: "%s",\n' % (name[2:], base64.b64encode(data).decode()))
        n += 1
    out.append("};\n")
    gen, _ = wad.get("GENMIDI")
    out.append("ASSETS.genmidi = \"%s\";\n" % base64.b64encode(gen).decode())
    out.append("ASSETS.music = {\n")
    m = 0
    for name, data in lumps_with("D_"):
        out.append('  %s: "%s",\n' % (name[2:], base64.b64encode(data).decode()))
        m += 1
    out.append("};\n")
    dst = os.path.join(os.path.dirname(__file__), "..", "assets", "audio.js")
    with open(dst, "w") as f:
        f.write("".join(out))
    print("wrote %s: %d sfx, %d songs, GENMIDI %d B" %
          (dst, n, m, len(gen)))


if __name__ == "__main__":
    main()
